version: '3.8'
services:

  gitlab-server:
    image: 'gitlab/gitlab-ce:latest'
    container_name: gitlab-server
    environment:
      GITLAB_ROOT_EMAIL: "godcandidate101@gmail.com" # user email
      GITLAB_ROOT_PASSWORD: "Abcd@0123456789"  # user password - at least 12 chars
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost:8000'
        nginx['listen_port'] = 8000
        gitlab_rails['gitlab_shell_ssh_port'] = 2222 
    ports:
      - '8000:8000'
      - '2222:22'    # SSH (Host 2222 → Container 22)
    volumes: # persists gitlab configs and data
      - ./gitlab/config:/etc/gitlab
      - ./gitlab/data:/var/opt/gitlab
    networks:
      - gitlab-in-docker

  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    container_name: gitlab-runner
    network_mode: 'host'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

      
networks: # a separate network for docker server and dnd to communicate
  gitlab-in-docker:
    name: gitlab-in-docker
    driver: bridge